services:
  # Web service for the full-stack application
  - type: web
    name: Sign Company
    runtime: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://sign-company-dashboard.onrender.com
      - key: GOOGLE_MAPS_API_KEY
        sync: false